name: Sync Proxies Folder

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Her saat başı çalıştırır

jobs:
  sync_proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Configure Git
        run: |
          git config --global user.name "handeveloper1"
          git config --global user.email "oguzhanyazman@gmail.com"

      - name: Remove old proxies folders (if exist)
        run: |
          rm -rf "Proxies-Ercin" "Proxy-hendrikbgr" "Proxy-Zaeem20" "Proxy-Tsprnay" "Proxy-gitrecon1455" "Proxy-KangProxy"

      - name: Clone only proxies folder
        run: |
          git clone --depth=1 https://github.com/ErcinDedeoglu/proxies.git temp_repo
          mkdir -p "Proxies-Ercin"
          mv temp_repo/proxies/*.txt "Proxies-Ercin"
          rm -rf temp_repo 

      - name: Download proxy_list.txt from hendrikbgr repo
        run: |
          mkdir -p "Proxy-hendrikbgr"
          curl -o "Proxy-hendrikbgr/proxy_list.txt" -L "https://raw.githubusercontent.com/hendrikbgr/Free-Proxy-Repo/master/proxy_list.txt"

      - name: Download proxies from Zaeem20 repo
        run: |
          mkdir -p "Proxy-Zaeem20"
          curl -o "Proxy-Zaeem20/https.txt" -L "https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/refs/heads/master/https.txt"

      - name: Download proxies from Tsprnay repo
        run: |
          mkdir -p "Proxy-Tsprnay"
          curl -o "Proxy-Tsprnay/https.txt" -L "https://raw.githubusercontent.com/Tsprnay/Proxy-lists/refs/heads/master/proxies/https.txt"

      - name: Download proxies from gitrecon1455 repo
        run: |
          mkdir -p "Proxy-gitrecon1455"
          curl -o "Proxy-gitrecon1455/proxies.txt" -L "https://raw.githubusercontent.com/gitrecon1455/ProxyScraper/refs/heads/main/proxies.txt"

      - name: Download proxies from KangProxy repo
        run: |
          mkdir -p "Proxy-KangProxy"
          curl -o "Proxy-KangProxy/https.txt" -L "https://raw.githubusercontent.com/officialputuid/KangProxy/refs/heads/KangProxy/https/https.txt"

      - name: Append update timestamp to README.md
        run: |
          echo "\nLast updated (UTC+0): $(date --utc +'%Y-%m-%d %H:%M:%S')" >> README.md
          echo "Last updated (UTC+3): $(date --date='3 hours' +'%Y-%m-%d %H:%M:%S')" >> README.md

      - name: Pull latest changes and push
        run: |
          git add "Proxies-Ercin" "Proxy-hendrikbgr" "Proxy-Zaeem20" "Proxy-Tsprnay" "Proxy-gitrecon1455" "Proxy-KangProxy" README.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Updated proxies and timestamp in README.md"
          git pull --rebase origin main || git rebase --skip
          git push origin main
