name: Sync Proxies Folder

on:
  workflow_dispatch:  # Elle çalıştırmak için
  schedule:
    - cron: '0 * * * *'  # Her saat başı çalıştırır

jobs:
  sync_proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Tüm geçmişi çekiyoruz ki rebase yapabilelim

      - name: Remove old proxies folder (if exists)
        run: |
          rm -rf proxies  # Önceki proxies klasörünü temizle

      - name: Clone only proxies folder
        run: |
          git clone --depth=1 https://github.com/ErcinDedeoglu/proxies.git temp_repo
          mkdir -p proxies
          mv temp_repo/proxies/*.txt proxies/  # Sadece .txt dosyalarını taşı
          rm -rf temp_repo  # Gereksiz klasörü sil

      - name: Count proxies and update README.md
        run: |
          # Sayıları al
          SOCKS4_COUNT=$(wc -l < proxies/socks4.txt)
          SOCKS5_COUNT=$(wc -l < proxies/socks5.txt)
          HTTP_COUNT=$(wc -l < proxies/http.txt)
          HTTPS_COUNT=$(wc -l < proxies/https.txt)

          # README.md'deki sayıları güncellemek için sed komutunu doğru yazalım
          sed -i "s|[`][0-9]*[`]\(.*\)SOCKS4|[$SOCKS4_COUNT]\1SOCKS4|" README.md
          sed -i "s|[`][0-9]*[`]\(.*\)SOCKS5|[$SOCKS5_COUNT]\1SOCKS5|" README.md
          sed -i "s|[`][0-9]*[`]\(.*\)HTTP|[$HTTP_COUNT]\1HTTP|" README.md
          sed -i "s|[`][0-9]*[`]\(.*\)HTTPS|[$HTTPS_COUNT]\1HTTPS|" README.md

      - name: Pull latest changes and push
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "handeveloper1"

          git add README.md proxies
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated proxies and README.md"

          # Güncellemeleri çek ve rebase yap
          git pull --rebase origin main || git rebase --skip
