name: Sync Proxies Folder

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Her saat başı çalıştırır

jobs:
  sync_proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Remove old proxies folders (if exist)
        run: |
          rm -rf "Proxies-Ercin" "Proxy-hendrikbgr"

      - name: Clone only proxies folder
        run: |
          git clone --depth=1 https://github.com/ErcinDedeoglu/proxies.git temp_repo
          mkdir -p "Proxies-Ercin"
          mv temp_repo/proxies/*.txt "Proxies-Ercin"
          rm -rf temp_repo 

      - name: Download proxy_list.txt from hendrikbgr repo
        run: |
          mkdir -p "Proxy-hendrikbgr"
          curl -o "Proxy-hendrikbgr/proxy_list.txt" -L "https://raw.githubusercontent.com/hendrikbgr/Free-Proxy-Repo/master/proxy_list.txt"

      - name: Count proxies and update README.md
        run: |
          SOCKS4_COUNT=$(wc -l < "Proxies-Ercin/socks4.txt")
          SOCKS5_COUNT=$(wc -l < "Proxies-Ercin/socks5.txt")
          HTTP_COUNT=$(wc -l < "Proxies-Ercin/http.txt")
          HTTPS_COUNT=$(wc -l < "Proxies-Ercin/https.txt")
          HENDRIK_COUNT=$(wc -l < "Proxy-hendrikbgr/proxy_list.txt")

          TOTAL_PROXIES=$((SOCKS4_COUNT + SOCKS5_COUNT + HTTP_COUNT + HTTPS_COUNT + HENDRIK_COUNT))
          CURRENT_DATE=$(date --utc +'%Y.%m.%d/%H:%M:%SZ')

          sed -i "s|\(SOCKS4\) *[0-9]*|\1 \`$SOCKS4_COUNT\`|g" README.md
          sed -i "s|\(SOCKS5\) *[0-9]*|\1 \`$SOCKS5_COUNT\`|g" README.md
          sed -i "s|\(HTTP\) *[0-9]*|\1 \`$HTTP_COUNT\`|g" README.md
          sed -i "s|\(HTTPS\) *[0-9]*|\1 \`$HTTPS_COUNT\`|g" README.md
          sed -i "s|\(Hendrik\) *[0-9]*|\1 \`$HENDRIK_COUNT\`|g" README.md

          sed -i "s|Total Proxies-[0-9]*|Total Proxies-$TOTAL_PROXIES|g" README.md
          sed -i "s|Total Proxies-[0-9]*-blue|Total Proxies-$TOTAL_PROXIES-blue|g" README.md

      - name: Pull latest changes and push
        run: |
          git config --global user.name "handeveloper1"
          git add README.md "Proxies-Ercin" "Proxy-hendrikbgr"
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Updated proxies and README.md"
          git pull --rebase origin main || git rebase --skip
          git push origin main
