name: Sync Proxies Folder

on:
  workflow_dispatch:  # Elle çalıştırmak için
  schedule:
    - cron: '0 * * * *'  # Her saat başı çalıştırır

jobs:
  sync_proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Tüm geçmişi çekiyoruz ki rebase yapabilelim

      - name: Remove old proxies folder (if exists)
        run: |
          rm -rf proxies  # Önceki proxies klasörünü temizle

      - name: Clone only proxies folder
        run: |
          git clone --depth=1 https://github.com/ErcinDedeoglu/proxies.git temp_repo
          mkdir -p proxies
          mv temp_repo/proxies/*.txt proxies/  # Sadece .txt dosyalarını taşı
          rm -rf temp_repo  # Gereksiz klasörü sil

      - name: Pull latest changes and push
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-username"

          git add proxies
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated proxies"

          # Güncellemeleri çek ve rebase yap
          git pull --rebase origin main || git rebase --skip

          # Push yap
          git push origin main
